{% set name = "madtequila" %}
{% set version = "1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

 
# adapt madpno source once online
source: 
        - path: ../../madsource/
          folder: madness
          git_tag: tequila
        - git_url: https://github.com/dpilger26/NumCpp.git
          folder: numcpp

build:
  number: 0
  always_include_files:
  - /etc/conda/activate.d/activate_madness.sh


requirements:
  run:
    - boost
    - mkl
  build:
    - {{ compiler('cxx') }}
    - python
    - cmake
    - make
    - mkl-devel
    - boost

about:
  home: "https://github.com/madness/madness"
  license: "GPL-2.0"
  license_family: "GPL"
  license_file: ""
  summary: "Madness with extra features for tequila use: see github.com/kottmanj/madness tequila branch"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - kottmanj
